-- 1. Bảng tác giả (authors) - Không thay đổi
CREATE TABLE authors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    bio TEXT NULL
);

-- 2. Bảng khách hàng (customers) - Sửa từ bảng 'users'
-- Bỏ cột 'is_admin' và đổi tên bảng
CREATE TABLE customers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(256) NULL,
    email VARCHAR(256) NULL UNIQUE
);

-- 3. Bảng sách (books) - Đã sửa đổi
CREATE TABLE books(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(50) NOT NULL,
    published_date TIMESTAMP NOT NULL,

    -- Sửa 'price' thành 'daily_rental_fee' (phí thuê mỗi ngày)
    daily_rental_fee REAL NOT NULL CHECK (daily_rental_fee >= 0),

    -- Thêm cột 'current_customer_id' để biết ai đang thuê (hoặc NULL = có sẵn)
    -- Điều này đảm bảo "mỗi quyển sách chỉ được thuê bởi một người" tại một thời điểm
    current_customer_id INT NULL,

    -- Ràng buộc khóa ngoại (Foreign Key)
    CONSTRAINT fk_books_authors
        FOREIGN KEY (author_id)
        REFERENCES authors(id)
        ON DELETE CASCADE, -- Nếu xóa tác giả, sách của họ cũng bị xóa

    CONSTRAINT fk_books_customers_renter
        FOREIGN KEY (current_customer_id)
        REFERENCES customers(id)
        ON DELETE SET NULL -- Nếu khách hàng bị xóa, sách tự động trở về trạng thái 'có sẵn'
);

-- 4. Bảng theo dõi thuê sách (book_rentals) - Bảng mới
CREATE TABLE book_rentals(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INT NOT NULL,
    customer_id INT NOT NULL,

    -- Ngày thuê (mặc định là thời điểm chèn)
    rental_date TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Hạn trả (ví dụ: 7 hoặc 14 ngày sau ngày thuê, logic này do ứng dụng quyết định)
    due_date TIMESTAMP NOT NULL,
    -- Ngày trả thực tế (sẽ là NULL cho đến khi khách trả sách)
    actual_return_date TIMESTAMP NULL,

    -- Ghi lại tiền thuê 1 ngày (tại thời điểm thuê)
    -- để tránh trường hợp sách thay đổi giá thuê trong tương lai
    daily_fee_at_rental REAL NOT NULL,

    -- Tổng tiền phải trả (tính khi trả sách, NULL nếu chưa trả)
    total_due REAL NULL,

    -- Trạng thái: 'renting' (đang thuê), 'overdue' (chậm trả), 'returned' (đã trả)
    status VARCHAR(20) NOT NULL DEFAULT 'renting',

    CONSTRAINT fk_rentals_books
        FOREIGN KEY (book_id)
        REFERENCES books(id)
        ON DELETE CASCADE, -- Nếu sách bị xóa, lịch sử thuê cũng xóa

    CONSTRAINT fk_rentals_customers
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE -- Nếu khách hàng bị xóa, lịch sử thuê cũng xóa
);