-- 1. tạo bảng tác giả (authors)
create table authors(
    -- 'int' và 'generated by default as identity' để tự tăng
    id int generated by default as identity primary key,
    name varchar(64) not null,
    birth_date timestamp not null,
    short_bio text null
);

-- 2. tạo bảng sách (books)
create table books(
    id int generated by default as identity primary key,
    author_id int not null,
    name varchar(128) not null,
    -- đổi 'type' (int) sang 'book_type' (varchar) để lưu chuỗi
    book_type varchar(50) not null, 
    published_date timestamp not null,
    price real not null,

    -- ràng buộc khóa ngoại
    constraint fk_books_authors
        foreign key (author_id) 
        references authors(id) 
        on delete cascade
);

-- 3. tạo bảng người dùng (users)
create table users(
    id int generated by default as identity primary key,
    username varchar(256) not null,
    -- đổi từ 'password_hash' (text) sang 'password' (text)
    password text not null,
    fullname varchar(256) null,
    email varchar(256) null,
    is_active boolean not null,
    is_admin boolean not null
);