CREATE TABLE authors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    bio TEXT NULL
);

CREATE TABLE customers(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(256) NULL,
    email VARCHAR(256) NULL UNIQUE
);

CREATE TABLE books(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT NOT NULL,
	current_customer_id INT NULL,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(50) NOT NULL,
    published_date TIMESTAMP NOT NULL,
    daily_rental_fee REAL NOT NULL CHECK (daily_rental_fee >= 0),

    CONSTRAINT fk_books_authors
        FOREIGN KEY (author_id)
        REFERENCES authors(id)
        ON DELETE CASCADE, 

    CONSTRAINT fk_books_customers
        FOREIGN KEY (current_customer_id)
        REFERENCES customers(id)
        ON DELETE SET NULL
);

CREATE TABLE book_rentals(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INT NOT NULL,
    customer_id INT NOT NULL,
    rental_date TIMESTAMP NOT NULL DEFAULT NOW(),
    due_date TIMESTAMP NOT NULL,
    actual_return_date TIMESTAMP NULL,
    daily_fee_at_rental REAL NOT NULL,
    total_fee REAL NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Renting', -- 'Returned', 'Overdue'

    CONSTRAINT fk_rentals_books
        FOREIGN KEY (book_id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_rentals_customers
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE
);